DROP TABLE IF EXISTS `{{ GCP_ANALYTICS_DATASET }}.{{MOVIES_METADATA_TABLE}}`;

CREATE TABLE IF NOT EXISTS
  `{{ GCP_ANALYTICS_DATASET }}.{{MOVIES_METADATA_TABLE}}`
CLUSTER BY
  `id`,
  `production_countries` AS
SELECT
  *
FROM
  `{{GCP_RAW_DATASET}}.{{MOVIES_METADATA_TABLE}}`;


DROP TABLE IF EXISTS `{{ GCP_ANALYTICS_DATASET }}.{{RATINGS_TABLE}}`;

CREATE TABLE IF NOT EXISTS
`{{ GCP_ANALYTICS_DATASET }}.{{RATINGS_TABLE}}`
CLUSTER BY
`movieId` AS
SELECT
*
FROM
`{{GCP_RAW_DATASET}}.{{RATINGS_TABLE}}`;
